"""Apply frozen Stage14A bottleneck decision rules and write the report."""
from __future__ import annotations
import argparse,json
from pathlib import Path
def load(p):return json.loads(Path(p).read_text(encoding="utf-8"))
def save(p,x):Path(p).write_text(json.dumps(x,indent=2,allow_nan=False)+"\n",encoding="utf-8")
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,required=True);a=p.parse_args();m=load(a.output/"subset_detector_metrics.json");fidelity_audit=load(a.output/"fidelity_audit.json");rows={x["arm"]:x for x in m["records"]};r=rows["random"]["map50_95"]
 delta={k:{"map50_95_raw":v["map50_95"]-r,"map50_95_pp":100*(v["map50_95"]-r),"per_class_ap50_95_pp":{c:100*(v["per_class"][c]["ap50_95"]-rows["random"]["per_class"][c]["ap50_95"]) for c in ("flash","black")}} for k,v in rows.items() if k!="random"}
 fidelity_protocol_complete=(fidelity_audit.get("crop_kid",{}).get("status")=="COMPLETE" and fidelity_audit.get("real_nearest_lpips",{}).get("status")=="COMPLETE")
 f=fidelity_protocol_complete and delta["high_fidelity"]["map50_95_raw"]>=.005 and delta["low_fidelity_diagnostic"]["map50_95_raw"]<0;c=delta["high_context_compatibility"]["map50_95_raw"]>=.005 and rows["high_context_compatibility"]["map50_95"]>max(rows["high_fidelity"]["map50_95"],rows["valid_novel"]["map50_95"]) and delta["low_context_diagnostic"]["map50_95_raw"]<0
 novelty=False # duplicate/off-manifold equal-budget arms were infeasible, so Case C cannot be asserted.
 status="CONTEXT_COMPATIBILITY_BOTTLENECK_SUPPORTED" if c else "FIDELITY_BOTTLENECK_SUPPORTED" if f else "VALID_NOVELTY_BOTTLENECK_SUPPORTED" if novelty else "IMAGE_PROPERTY_BOTTLENECK_NOT_IDENTIFIED"
 out={"status":status,"random_map50_95":r,"deltas_vs_random":delta,"gates":{"fidelity":f,"context_compatibility":c,"valid_novelty":novelty},"fidelity_protocol_complete":fidelity_protocol_complete,"morphology_matched_subset_signal":{"high_minus_random_pp":delta["high_fidelity"]["map50_95_pp"],"low_minus_random_pp":delta["low_fidelity_diagnostic"]["map50_95_pp"],"interpretation":"diagnostic signal only; the current subset was selected by morphology distance because crop-KID and real-nearest LPIPS were unavailable"},"fidelity_claim_blocked_reason":None if fidelity_protocol_complete else "crop-KID and real-nearest LPIPS were not computed; morphology matching alone cannot establish the broad fidelity bottleneck","novelty_causal_gate_unavailable":"duplicate-like and off-manifold equal-budget subsets infeasible","STAGE14B_AUTO_START":False,"deep_pcb_training_count":0,"deep_pcb_generation_count":0};save(a.output/"bottleneck_comparison.json",out);save(a.output/"stage14a_status.json",out)
 recommendation={"FIDELITY_BOTTLENECK_SUPPORTED":"fidelity mechanism","CONTEXT_COMPATIBILITY_BOTTLENECK_SUPPORTED":"context-adaptive mechanism","VALID_NOVELTY_BOTTLENECK_SUPPORTED":"valid-novelty mechanism","IMAGE_PROPERTY_BOTTLENECK_NOT_IDENTIFIED":"generation-time task-aware optimization"}[status]
 lines=["# Plastic_Bomo Stage14A Generator Bottleneck Audit","",f"Status: **{status}**.","",f"Recommended next direction: **{recommendation}**.","","## Equal-budget seed42 screening","", "| Arm | mAP50-95 | Delta vs Random (pp) |","|---|---:|---:|"]
 for k,v in rows.items():lines.append(f"| {k} | {v['map50_95']:.6f} | {0 if k=='random' else delta[k]['map50_95_pp']:+.3f} |")
 lines += ["",f"Fidelity protocol complete: **{fidelity_protocol_complete}**. The morphology-matched high/low contrast is retained as diagnostic evidence, but it is not labeled broad fidelity evidence unless crop-KID and real-nearest LPIPS are complete.","","Novelty was diagnostic only: duplicate-like and off-manifold groups could not supply 40 samples/class, so no novelty causal claim was made.","","All trained arms used the same 138 real images, 80 extras (40/class), YOLO11s initialization, seed42, 150 epochs, batch 1, and final `last.pt`. Official validation was used only after training. DeepPCB training/generation count remained zero. Stage14B was not started."]
 (a.output/"STAGE14A_REPORT.md").write_text("\n".join(lines)+"\n",encoding="utf-8");print(json.dumps(out,indent=2))
if __name__=="__main__":main()
