"""Determine Stage9D dead-adapter root cause from frozen audit outputs."""
from __future__ import annotations
import argparse,json
from pathlib import Path
def load(p):return json.loads(Path(p).read_text())
def save(p,x):Path(p).write_text(json.dumps(x,indent=2,allow_nan=False))
def main():
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,required=True);a=p.parse_args();param=load(a.output/"checkpoint_parameter_state.json");init=load(a.output/"checkpoint_vs_initialization.json");mask=load(a.output/"mask_survival_audit.json");hook=load(a.output/"hook_execution_audit.json");grad=load(a.output/"single_batch_gradient_audit.json");step=load(a.output/"one_step_update_audit.json");traj=load(a.output/"diagnostic_50step_trajectory.json");amp=load(a.output/"amp_skip_audit.json");arm=load(a.output/"stage9a_effective_arm_reinterpretation.json")
 projection_zero=all(param[c]["projection_weights_and_biases_exact_zero"] for c in ("short","pinhole"));entire_unchanged=all(init[c]["all_exact_equal"] for c in ("short","pinhole"));nonfinite_gradient=any(grad[c]["status"]=="NONFINITE_GRADIENT" for c in ("short","pinhole"));gradient_reaches=all(grad[c]["status"]=="GRADIENT_REACHES_PROJECTION" for c in ("short","pinhole"));one_step_works=all(step[c].get("post_step_parameters_finite",False) and step[c]["projection_weight_changed"] and not step[c]["post_step_output_still_exact_zero"] for c in ("short","pinhole"));save_load_ok=all(step[c]["state_dict_roundtrip_exact_equal"] for c in ("short","pinhole"));mask_collapse=mask["status"]=="MASK_DOWNSAMPLE_COLLAPSE_SUPPORTED";hooks_ok=all(hook[c][v]["hook_called_count"]==2 and all(x["condition_set_before_hook"] for x in hook[c][v]["calls"]) for c in ("short","pinhole") for v in ("fresh","trained"));trajectory_updates=traj.get("successful_updates",0)>0;amp_collapse=amp["status"] in ("AMP_SCALE_COLLAPSED_TO_ZERO","ALL_UPDATES_SKIPPED_NONFINITE")
 causes=[]
 if nonfinite_gradient and amp_collapse:causes.append("NONFINITE_GRADIENT_AMP_SCALE_COLLAPSE")
 if projection_zero and gradient_reaches and one_step_works:causes.append("ZERO_PROJECTION_TRAINING_FAILURE")
 if mask_collapse:causes.append("MASK_SUPPORT_COLLAPSE")
 if not hooks_ok:causes.append("HOOK_OR_CONDITIONING_FAILURE")
 if not save_load_ok:causes.append("CHECKPOINT_SAVE_LOAD_FAILURE")
 status="MULTIPLE_IMPLEMENTATION_FAILURES" if len(causes)>1 else causes[0] if causes else "NO_CLEAR_DEAD_ADAPTER_CAUSE";doc={"status":status,"evidence":{"formal_projection_state_exact_zero":projection_zero,"entire_formal_adapter_matches_fresh_initialization":entire_unchanged,"fresh_nonfinite_gradient":nonfinite_gradient,"fresh_gradient_reaches_projection":gradient_reaches,"fresh_one_step_makes_finite_nonzero_residual":one_step_works,"diagnostic_successful_updates":traj.get("successful_updates",0),"diagnostic_parameters_update":trajectory_updates,"diagnostic_stopped_on_zero_scale":traj.get("stopped_on_zero_scale",False),"mask_support_collapse":mask_collapse,"hooks_and_conditions_execute":hooks_ok,"state_dict_roundtrip_preserves_values_including_nan":save_load_ok,"amp_skip_status":amp["status"]},"contributing_statuses":causes,"UNADAPTED_PRETRAINED_BACKBONE_INSUFFICIENT":True,"FULL_UNET_FINETUNING_REQUIRED":False,"LORA_REQUIRED":False,"historical_stage9a_stage9c_modified":False,"detector_training_count":0,"official_validation_use_count":0};save(a.output/"stage9d_status.json",doc)
 lines=["# DeepPCB Stage9D Dead Adapter Root-Cause Audit","",f"Status: **{status}**.","","## Decision evidence",""]+[f"- {k}: {v}" for k,v in doc["evidence"].items()]+["","The Stage9A arm remains formally failed and is reinterpreted as an unadapted pretrained-backbone control because its learned residual path was inactive.","UNADAPTED_PRETRAINED_BACKBONE_INSUFFICIENT=true, but neither full-UNet fine-tuning nor LoRA is declared required: the lightweight path never received a valid empirical test.","VAE_BOTTLENECK_NOT_SUPPORTED remains frozen from Stage9C. All subsequent fidelity work must use the Stage7B/8B adaptive padded crop protocol.","","No detector, formal 2,000-step model, new architecture, LoRA, or official-validation experiment was run."];(a.output/"STAGE9D_REPORT.md").write_text("\n".join(lines)+"\n");print(json.dumps(doc,indent=2))
if __name__=="__main__":main()
