"""Pre-register Stage9A gates and write code-backed training audits."""
from __future__ import annotations
import argparse,json,hashlib
from pathlib import Path
import torch
from diffusers import UNet2DConditionModel
from stage9a_frozen_adapter import FrozenResidualAdapter

def save(p,x):p.write_text(json.dumps(x,indent=2))
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--base_model",type=Path,required=True);p.add_argument("--sd2_models",type=Path,required=True);p.add_argument("--msdf_models",type=Path,required=True);p.add_argument("--output",type=Path,required=True);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=True)
 base=UNet2DConditionModel.from_pretrained(a.base_model,subfolder="unet",torch_dtype=torch.float32);adapter=FrozenResidualAdapter();ap=sum(x.numel() for x in adapter.parameters());bp=sum(x.numel() for x in base.parameters())
 audit={"evidence_source":"train_rda.py and checkpoint metadata","vanilla_sd2":{"unet":"full trainable","vae":"frozen","text_encoder":"frozen","optimizer":"AdamW","unet_lr":5e-6,"updates_per_class":2000},"full_msdf":{"unet":"full trainable","vae":"frozen","text_encoder":"frozen","optimizer_groups":{"full_unet":5e-6,"msdf":1e-4},"updates_per_class":2000},"source_identity_can_be_written_into_unet":True,"reason":"all UNet parameters require gradients and are in AdamW group 0; each class is fine-tuned from only its low-shot examples","historical_gradient_data_unavailable":True}
 save(a.output/"sd2_training_parameter_audit.json",audit)
 arch={"name":"FrozenResidualAdapter","condition_inputs":["target_mask","paired_normal_context","diffusion_timestep"],"forbidden_inputs":["real_defect_reference","detector_feature","morphology_template","source_identity","teacher_or_selector_score"],"backbone":{"unet":"100% frozen","vae":"100% frozen","text_encoder":"100% frozen"},"injection":{"unet_up_blocks":[2,3],"count":2,"zero_initialized":True,"rms_bound_ratio":.10},"fusion":"additive mask/context/time features","attention_layers":0,"new_losses":0}
 save(a.output/"frozen_adapter_architecture.json",arch);save(a.output/"frozen_adapter_parameter_audit.json",{"adapter_parameters":ap,"unet_parameters":bp,"ratio":ap/bp,"prototype_only":True})
 gate={"registered_before_stage9a_generation_and_metrics":True,"status_options":["FROZEN_ADAPTER_FEASIBLE","FROZEN_ADAPTER_MIXED","FROZEN_ADAPTER_NOT_FEASIBLE"],"axes_are_never_weighted":True,"per_class_required":["short","pinhole"],"criteria":{"no_clear_fidelity_collapse":{"lpips_ratio_vs_sd2_max":1.10,"edge_cosine_delta_vs_sd2_min":-0.02,"boundary_gradient_cosine_delta_vs_sd2_min":-0.02},"diversity_increase_vs_full_msdf":{"ic_lpips_ratio_min":1.05,"feature_variance_ratio_min":1.05},"source_identity_dominance_down_vs_full_msdf":{"top1_retrieval_delta_max":-0.02,"within_total_ratio_delta_max":-0.02},"task_feature_not_notably_worse_than_sd2":{"normalized_pair_gap_ratio_max":1.10,"fraction_gt_q95_delta_max":0.05},"class_consistency":"every hard criterion must pass independently for short and pinhole"},"decision":{"FROZEN_ADAPTER_FEASIBLE":"all criteria pass for both classes","FROZEN_ADAPTER_NOT_FEASIBLE":"fidelity collapse or task support failure in either class, or no diversity/memorization improvement in both classes","FROZEN_ADAPTER_MIXED":"all remaining outcomes"},"stage9b_authorized_only_if":"FROZEN_ADAPTER_FEASIBLE"}
 save(a.output/"stage9a_gate_protocol.json",gate);save(a.output/"method_difference_table.json",{"local_verified":{"Vanilla_SD2":"full UNet fine-tuning; no added adapter","Full_MSDF_v3":"full UNet fine-tuning plus reference-conditioned multi-scale guidance","FrozenResidualAdapter":"frozen UNet; mask+normal-context+timestep only; two high-resolution residual sites"},"external":{"DualAnoDiff":{"external_baseline_verification_required":True},"AnomalyDiffusion":{"external_baseline_verification_required":True},"DefectFill":{"external_baseline_verification_required":True}}})
 (a.output/"method_difference_table.md").write_text("# Stage9A local method difference\n\n| Method | Backbone update | Allowed condition | Stage9A role |\n|---|---|---|---|\n| Vanilla SD2 | Full UNet | mask, normal image, text, timestep | existing control |\n| Full MSDF-v3 | Full UNet + MSDF | includes defect reference | existing diagnostic control |\n| FrozenResidualAdapter | none | mask, paired normal context, timestep | new prototype |\n\nDualAnoDiff, AnomalyDiffusion and DefectFill require external baseline verification; no unverified architectural claims are made.\n")
 print(json.dumps({"status":"STAGE9A_PREREGISTERED","adapter_parameters":ap},indent=2))
if __name__=="__main__":main()
