"""Stage10A-R pair-independent real-only OOF manifold recalibration."""
from __future__ import annotations
import argparse,json
from collections import Counter,defaultdict
from pathlib import Path
import numpy as np
from calibrate_deeppcb_stage10a import CLASSES,load,save,sha,stats,quant,cv,wasserstein_1d,ks_1d

def main():
 p=argparse.ArgumentParser()
 for n in ("protocol","stage3r","folds","lowdata","stage10a","output"):p.add_argument("--"+n,type=Path,required=True)
 a=p.parse_args();a.output.mkdir(parents=True,exist_ok=True);cfg=load(a.protocol);assert cfg["real_only"] and cfg["neighbor_rule"].endswith("different physical_pair_id")
 manifest=load(a.stage3r/"oof_feature_bank_manifest_corrected.json");folds=load(a.folds);low=load(a.lowdata);folddef={int(x["fold"]):x for x in folds["folds"]};assert manifest["official_val_use_count"]==folds["official_val_use_count"]==0 and folds["selected_ids_sha256"]==low["selected_ids_sha256"]
 rows=[]
 for fm in manifest["folds"]:
  fold=int(fm["fold"]);z=np.load(a.stage3r/f"oof_real_bank_corrected_fold{fold}.npz",allow_pickle=False);F=z["features"].astype(float);F/=np.linalg.norm(F,axis=1,keepdims=True)
  assert len(F)==len(fm["records"])
  for r,f,c in zip(fm["records"],F,z["class_ids"]):
   assert r["pair_id"] in folddef[fold]["holdout_pair_ids"] and r["pair_id"] not in folddef[fold]["train_pair_ids"] and int(r["class_id"])==int(c);rows.append({**r,"class_name":CLASSES[int(c)],"feature":f})
 assert len(rows)==775 and len({x["instance_id"] for x in rows})==775
 groups=defaultdict(list)
 for i,r in enumerate(rows):groups[(r["fold"],r["class_id"])].append(i)
 suff=[]
 for r in rows:
  candidates=[i for i in groups[(r["fold"],r["class_id"])] if rows[i]["pair_id"]!=r["pair_id"]];suff.append({"fold":r["fold"],"class_name":r["class_name"],"instance_id":r["instance_id"],"pair_id":r["pair_id"],"candidate_neighbor_count":len(candidates),"k10_available":len(candidates)>=10})
 counts=[x["candidate_neighbor_count"] for x in suff];supported=all(x["k10_available"] for x in suff);max_common=min(counts);effective_k=10 if supported else max_common;suff_status="PAIR_INDEPENDENT_K10_SUPPORTED" if supported else "PAIR_INDEPENDENT_K10_INSUFFICIENT"
 save(a.output/"pair_independent_neighbor_sufficiency.json",{"status":suff_status,"requested_k10":True,"effective_max_k":effective_k,"summary":{"minimum":min(counts),"q05":float(np.quantile(counts,.05)),"median":float(np.median(counts)),"mean":float(np.mean(counts))},"per_fold_class":{f"fold{f}_{CLASSES[c]}":{"minimum":min(x["candidate_neighbor_count"] for x in suff if x["fold"]==f and x["class_name"]==CLASSES[c]),"instances":sum(x["fold"]==f and x["class_name"]==CLASSES[c] for x in suff)} for f,c in groups},"records":suff})
 local=[];relations=[];random_rel=[];rng=np.random.default_rng(cfg["random_neighbor_seed"])
 for (fold,c),idx in groups.items():
  for i in idx:
   candidates=[j for j in idx if rows[j]["pair_id"]!=rows[i]["pair_id"]];d=np.maximum(0.,1-np.stack([rows[j]["feature"] for j in candidates])@rows[i]["feature"]);order=np.argsort(d);ds=d[order[:effective_k]];ids=[candidates[j] for j in order[:effective_k]];r5=float(ds[:5].mean());rec={"instance_id":rows[i]["instance_id"],"pair_id":rows[i]["pair_id"],"fold":fold,"class_id":int(c),"class_name":CLASSES[c],"candidate_neighbor_count":len(candidates),"d1":float(ds[0]),"k3_radius":float(ds[:3].mean()),"k5_radius":r5,"k10_radius":float(ds[:10].mean()) if effective_k>=10 else None,"neighbor_instance_ids":[rows[j]["instance_id"] for j in ids],"neighbor_pair_ids":[rows[j]["pair_id"] for j in ids]};assert all(x!=rec["pair_id"] for x in rec["neighbor_pair_ids"]);local.append(rec)
   for rank,(dd,j) in enumerate(zip(ds[:5],ids[:5]),1):relations.append({"instance_id":rec["instance_id"],"pair_id":rec["pair_id"],"class_name":CLASSES[c],"fold":fold,"neighbor_instance_id":rows[j]["instance_id"],"neighbor_pair_id":rows[j]["pair_id"],"rank":rank,"distance":float(dd),"normalized_by_instance_k5":float(dd/r5)})
   j=int(rng.choice(candidates));dd=max(0.,1-float(rows[i]["feature"]@rows[j]["feature"]));random_rel.append({"instance_id":rec["instance_id"],"pair_id":rec["pair_id"],"class_name":CLASSES[c],"fold":fold,"neighbor_instance_id":rows[j]["instance_id"],"neighbor_pair_id":rows[j]["pair_id"],"distance":dd,"normalized_by_instance_k5":float(dd/r5)})
 save(a.output/"pair_independent_local_radius.json",{"primary_candidate":"pair-independent k5_radius","neighbor_rule":cfg["neighbor_rule"],"effective_max_k":effective_k,"records":local})
 old=load(a.stage10a/"local_manifold_radius.json")["records"];oldby={x["instance_id"]:x for x in old};pair_of={x["instance_id"]:x["pair_id"] for x in rows};paired=[]
 for x in local:
  o=oldby[x["instance_id"]];same=sum(pair_of[n]==x["pair_id"] for n in o["neighbor_instance_ids"][:5]);paired.append({"instance_id":x["instance_id"],"class_name":x["class_name"],"pair_id":x["pair_id"],"original_d1":o["d1"],"pair_independent_d1":x["d1"],"d1_delta":x["d1"]-o["d1"],"original_k5":o["k5_radius"],"pair_independent_k5":x["k5_radius"],"k5_delta":x["k5_radius"]-o["k5_radius"],"original_top1_same_pair":pair_of[o["neighbor_instance_ids"][0]]==x["pair_id"],"original_top5_same_pair_count":same})
 contamination={"original_top1_same_pair_count":sum(x["original_top1_same_pair"] for x in paired),"original_top1_same_pair_fraction":float(np.mean([x["original_top1_same_pair"] for x in paired])),"original_top5_contains_same_pair_count":sum(x["original_top5_same_pair_count"]>0 for x in paired),"original_top5_contains_same_pair_fraction":float(np.mean([x["original_top5_same_pair_count"]>0 for x in paired])),"class_wise":{c:{"top1_fraction":float(np.mean([x["original_top1_same_pair"] for x in paired if x["class_name"]==c])),"top5_contaminated_fraction":float(np.mean([x["original_top5_same_pair_count"]>0 for x in paired if x["class_name"]==c])),"mean_k5_delta":float(np.mean([x["k5_delta"] for x in paired if x["class_name"]==c]))} for c in CLASSES},"k5_radius_mean_delta":float(np.mean([x["k5_delta"] for x in paired])),"k5_radius_median_delta":float(np.median([x["k5_delta"] for x in paired])),"records":paired};save(a.output/"same_pair_contamination_audit.json",contamination)
 dist={}
 for scope in ("overall",)+CLASSES:
  z=[x for x in local if scope=="overall" or x["class_name"]==scope];dist[scope]={m:stats([x[m] for x in z]) for m in ("d1","k3_radius","k5_radius")};dist[scope]["k10_radius"]=stats([x["k10_radius"] for x in z]) if effective_k>=10 else {"available":False}
 save(a.output/"pair_independent_radius_distribution.json",{"metrics":dist})
 norm={}
 for scope in ("overall",)+CLASSES:
  lr=[x for x in local if scope=="overall" or x["class_name"]==scope];nr=[x for x in relations if scope=="overall" or x["class_name"]==scope];rr=[x for x in random_rel if scope=="overall" or x["class_name"]==scope];norm[scope]={"nearest_independent_neighbor":quant([x["d1"]/x["k5_radius"] for x in lr]),"top5_independent_neighbor_relations":quant([x["normalized_by_instance_k5"] for x in nr]),"random_independent_same_fold_same_class":quant([x["normalized_by_instance_k5"] for x in rr])}
 save(a.output/"pair_independent_normalized_real_variation.json",{"normalizer":"pair-independent instance k5 radius","same_pair_relations":0,"metrics":norm,"top5_relation_count":len(relations),"random_seed":cfg["random_neighbor_seed"]})
 nearest=[x["d1"]/x["k5_radius"] for x in local];top5=[x["normalized_by_instance_k5"] for x in relations];q05=float(np.quantile(nearest,.05));med=float(np.median(nearest));floor="NONZERO_VARIATION_FLOOR_SUPPORTED" if q05>=.10 and med>=.25 else "VARIATION_FLOOR_WEAK" if q05>0 and med>=.10 else "NO_VARIATION_FLOOR_SUPPORTED";lower=q05 if floor=="NONZERO_VARIATION_FLOOR_SUPPORTED" else 0.
 save(a.output/"pair_independent_lower_bound_feasibility.json",{"status":floor,"nearest_normalized_q05":q05,"nearest_normalized_median":med,"absolute_d1":stats([x["d1"] for x in local]),"old_lower_beta_historical_only":load(a.stage10a/"trust_region_candidates.json")["candidates"][0]["lower_beta"],"selected_new_lower_beta":lower,"rule":cfg["variation_floor_rules"]})
 global_r=float(np.median([x["k5_radius"] for x in local]));class_r={c:float(np.median([x["k5_radius"] for x in local if x["class_name"]==c])) for c in CLASSES};ri={x["instance_id"]:x["k5_radius"] for x in local};definitions={"global":lambda x:global_r,"class-adaptive":lambda x:class_r[x["class_name"]],"instance-adaptive":lambda x:ri[x["instance_id"]]};comparison={}
 for name,den in definitions.items():
  vals={c:np.asarray([x["distance"]/den(x) for x in relations if x["class_name"]==c]) for c in CLASSES};m=[float(np.median(vals[c])) for c in CLASSES];pairs=[(x,y) for i,x in enumerate(CLASSES) for y in CLASSES[i+1:]];comparison[name]={"mean_pairwise_class_wasserstein":float(np.mean([wasserstein_1d(vals[x],vals[y]) for x,y in pairs])),"class_median_spread":float(max(m)-min(m)),"mean_within_class_cv":float(np.mean([cv(vals[c]) for c in CLASSES])),"mean_pairwise_ks_statistic":float(np.mean([ks_1d(vals[x],vals[y]) for x,y in pairs])),"class_medians":dict(zip(CLASSES,m))}
 best=min(x["mean_pairwise_class_wasserstein"] for x in comparison.values())
 if comparison["global"]["mean_pairwise_class_wasserstein"]<=1.1*best:choice="global"
 elif comparison["class-adaptive"]["mean_pairwise_class_wasserstein"]<=1.1*comparison["instance-adaptive"]["mean_pairwise_class_wasserstein"]:choice="class-adaptive"
 else:choice="instance-adaptive"
 unstable=(not supported) or sum(dist[c]["k5_radius"]["std"]/dist[c]["k5_radius"]["mean"]>1 for c in CLASSES)>=4
 save(a.output/"pair_independent_radius_normalization_comparison.json",{"selection":choice,"selection_rule":cfg["normalization_selection_rule"],"global_radius_median_k5":global_r,"class_radius_median_k5":class_r,"metrics":comparison,"real_manifold_unstable":unstable})
 bands=[]
 for name,q in (("conservative",.75),("medium",.90),("wide",.95)):
  upper=float(np.quantile(top5,q));bands.append({"name":name,"lower_beta":lower,"upper_beta":upper,"real_independent_top5_relation_coverage":float(np.mean([(lower<=x<=upper) for x in top5])),"relations":len(top5),"lower_basis":"independent nearest q05" if lower else "zero because nonzero floor unsupported","upper_basis":f"independent top5 q{int(q*100)}"})
 save(a.output/"pair_independent_trust_region_candidates.json",{"frozen_before_stage10b":True,"radius":"pair-independent instance k5 radius","candidates":bands,"synthetic_inputs_used":0})
 oldstatus=load(a.stage10a/"stage10a_status.json");oldbands=load(a.stage10a/"trust_region_candidates.json")["candidates"];oldcomp=load(a.stage10a/"radius_normalization_comparison.json");pairs_beta=[("lower_beta",oldbands[0]["lower_beta"],bands[0]["lower_beta"])]+[(f"{x['name']}_upper_beta",o["upper_beta"],x["upper_beta"]) for o,x in zip(oldbands,bands)];changes={n:{"stage10a":o,"stage10ar":n0,"relative_change":abs(n0-o)/abs(o)} for n,o,n0 in pairs_beta};robust=choice==oldstatus["frozen_future_protocol"] and floor==oldstatus["variation_floor_status"] and all(x["relative_change"]<=cfg["cross_version_finite_relative_change"] for x in changes.values());version_status="STAGE10A_CONCLUSION_ROBUST" if robust else "PAIR_EXCLUSION_MATERIALLY_CHANGES_CALIBRATION"
 cross={"status":version_status,"rule":cfg["cross_version_robust_rule"],"normalization":{"stage10a":oldstatus["frozen_future_protocol"],"stage10ar":choice},"variation_floor":{"stage10a":oldstatus["variation_floor_status"],"stage10ar":floor},"beta_changes":changes,"top5_coverage":{"stage10a":[x["real_top5_relation_coverage"] for x in oldbands],"stage10ar":[x["real_independent_top5_relation_coverage"] for x in bands]},"selected_normalization_metrics":{"stage10a":oldcomp["metrics"][oldstatus["frozen_future_protocol"]],"stage10ar":comparison[choice]},"local_k5_radius":{"stage10a_mean":load(a.stage10a/"real_radius_distribution.json")["metrics"]["overall"]["k5_radius"]["mean"],"stage10a_median":load(a.stage10a/"real_radius_distribution.json")["metrics"]["overall"]["k5_radius"]["q50"],"stage10ar_mean":dist["overall"]["k5_radius"]["mean"],"stage10ar_median":dist["overall"]["k5_radius"]["q50"]}};save(a.output/"stage10a_vs_stage10ar_comparison.json",cross)
 status="PAIR_INDEPENDENT_REAL_MANIFOLD_UNSTABLE" if unstable else {"global":"GLOBAL_PAIR_INDEPENDENT_TRUST_REGION_SUFFICIENT","class-adaptive":"CLASS_ADAPTIVE_PAIR_INDEPENDENT_TRUST_REGION_SUPPORTED","instance-adaptive":"INSTANCE_ADAPTIVE_PAIR_INDEPENDENT_TRUST_REGION_SUPPORTED"}[choice];authorized=audit_pass=manifest["official_val_use_count"]==0 and supported and not unstable and len(bands)>0
 st={"status":status,"cross_version_status":version_status,"frozen_future_protocol":choice,"variation_floor_status":floor,"neighbor_sufficiency_status":suff_status,"OOF_FEATURE_AUDIT_PASS":audit_pass,"STAGE10B_GENERATOR_FEASIBILITY_AUTHORIZED":authorized,"synthetic_inputs_used":0,"official_validation_use_count":0,"generator_training_count":0,"detector_training_count":0,"stage10a_historical_results_modified":False};save(a.output/"stage10ar_status.json",st)
 report=["# DeepPCB Stage10A-R Pair-Independent Manifold Recalibration","",f"Status: **{status}**",f"Cross-version: **{version_status}**",f"Stage10B feasibility authorized: **{authorized}**","",f"All 775 sources support pair-independent k10; minimum candidate count is {min(counts)}.",f"Original top1 same-pair contamination: {contamination['original_top1_same_pair_fraction']:.2%}.",f"Original top5 same-pair contamination: {contamination['original_top5_contains_same_pair_fraction']:.2%}.",f"Mean k5-radius increase after pair exclusion: {contamination['k5_radius_mean_delta']:.6f}.","","## Re-frozen pair-independent bands","","| band | lower beta | upper beta | coverage |","|---|---:|---:|---:|"]+[f"| {x['name']} | {x['lower_beta']:.6f} | {x['upper_beta']:.6f} | {x['real_independent_top5_relation_coverage']:.4f} |" for x in bands]+["","Only Stage10A-R values are authorized for future Stage10B. Stage10A remains an unchanged historical audit. No synthetic, detector, generator, official validation, or downstream utility input was used."]
 (a.output/"STAGE10AR_REPORT.md").write_text("\n".join(report)+"\n",encoding="utf-8");print(json.dumps(st,indent=2))
if __name__=="__main__":main()
